### ISSUE TITLE
improve linking between different docs

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/laxar-dox#13]
We want to support simple linking within one file and between different files. It should be simple to get links for modules, module members, types and members of types.

The following tags should support linking:
- [x]  the `{@link ... }` / `{@linkplain ... }` tag for manual inline text linking
- [x] `@extends` tags for inheritance
- [x] `@param` and `@return` where a type is also documented within laxar
- [x] Modules and their respective members should also be linkable
  - [x] this should contain a test, that not two modules share the same name

**Comment by alex3683** [comment]
Implemented on `master` (`v2.0.0`)
